# The test environment was set up in docker-compose.yml which gives the ability
# to use the same config for remote and local tests.
# Specifics of the server environment were set up in Dockerfile which gives the ability
# to use the same docker container in production and for tests.
version: 2
jobs:
  build:
    working_directory: /app
    docker:
    - image: docker/compose:1.16.1
    steps:
    - checkout            # Pull the code of the app
    - setup_remote_docker # Creates isolated environment
    - run:
        name: Build containers
        command: docker-compose build
    - run:
        name: Run lint
        command: docker-compose run app npm run lint
    - run:
        name: Wait for DB start
        command: docker-compose run wait-for-db
    - run:
        name: Run tests
        command: docker-compose run app npm test
